'use client'

import Link from 'next/link'
import { ArrowLeft, BookOpen, Check, ChevronLeft, Clock3, Compass, Flame, Home, Search, Target, TrendingUp, UserRound } from 'lucide-react'
import { ImageBlock, DialogueBlock, VocabularyBlock, GrammarNote, ListeningBlock, PracticeBlock, SpeakingPrompt, LessonSummary } from './lesson-blocks'

const topics = [
  { title: 'Everyday Life', fa: 'زندگی روزمره', progress: '۳ / ۵ درس', state: 'done' },
  { title: 'Food & Restaurants', fa: 'غذا و رستوران', progress: '۳ / ۷ درس', state: 'current' },
  { title: 'Travel Basics', fa: 'مقدمات سفر', progress: 'شروع نشده', state: 'upcoming' },
  { title: 'Friends & Social Life', fa: 'دوستی و روابط اجتماعی', progress: 'شروع نشده', state: 'upcoming' },
  { title: 'Work Basics', fa: 'مقدمات محیط کار', progress: 'شروع نشده', state: 'upcoming' },
]
const lessons = ['Ordering at a Café', 'Asking for the Menu', 'Making a Reservation', 'Talking About Preferences', 'Paying the Bill', 'Review', 'Speaking Challenge']
const explore = ['Travel', 'Daily Life', 'Food', 'Work', 'Social', 'Pronunciation', 'Grammar', 'Vocabulary']

export function LearnApp({ initialView = 'path' }: { initialView?: 'path' | 'explore' | 'topic' | 'lesson' }) {
  const view = initialView
  return <div dir="rtl" className="min-h-screen bg-[#f8fafc] text-[#0f172a]"><div className="mx-auto flex min-h-screen max-w-[1440px]"><Sidebar /><main className="min-w-0 flex-1 pb-24 lg:pb-0"><div className="mx-auto max-w-5xl px-5 py-6 sm:px-8 lg:px-12 lg:py-10">{view === 'lesson' ? <LessonPage /> : view === 'topic' ? <TopicPage /> : <LearnHome view={view} />}</div></main></div><MobileNav /></div>
}

function ShellHeader({ title, subtitle }: { title: string; subtitle: string }) { return <header className="mb-8 flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm text-[#64748b]"><Link href="/" className="hover:text-indigo-600">یادگیری</Link><ChevronLeft className="size-4" /></div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-[#64748b] sm:text-base">{subtitle}</p></div><div className="hidden size-11 items-center justify-center rounded-2xl border border-[#e2e8f0] bg-white text-[#64748b] sm:flex"><Flame className="size-5 text-orange-400" /></div></header> }
function LearnHome({ view }: { view: 'path' | 'explore' }) { return <><ShellHeader title="یادگیری" subtitle="مسیر خودت را بساز؛ بدون عجله، با موقعیت‌های واقعی." /><div className="mb-8 flex w-fit rounded-2xl bg-[#eef0f7] p-1"><Link href="/learn" className={`rounded-xl px-5 py-2.5 text-sm font-bold ${view === 'path' ? 'bg-white text-indigo-600 shadow-sm' : 'text-[#64748b]'}`}>مسیر من</Link><Link href="/learn/explore" className={`rounded-xl px-5 py-2.5 text-sm font-bold ${view === 'explore' ? 'bg-white text-indigo-600 shadow-sm' : 'text-[#64748b]'}`}>Explore</Link></div>{view === 'path' ? <PathView /> : <ExploreView />}</> }
function PathView() { return <><section className="mb-8 rounded-[24px] bg-[#4f46e5] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-indigo-100">مسیر پیشنهادی برای سطح A2</p><h2 className="mt-2 text-xl font-bold">هر موضوع، یک قدم به مکالمه نزدیک‌تر</h2></div><Target className="size-7 text-indigo-200" /></div><div className="mt-5 h-2 rounded-full bg-indigo-400/40"><div className="h-full w-[38%] rounded-full bg-white" /></div><p className="mt-3 text-xs text-indigo-100">۳ از ۱۲ درس کامل شده</p></section><div className="relative flex flex-col gap-3">{topics.map((topic, index) => <Link href={topic.state === 'current' ? '/learn/topic/food' : '#'} key={topic.title} className={`relative flex items-center gap-4 rounded-[20px] border p-4 transition ${topic.state === 'current' ? 'border-indigo-200 bg-white shadow-[0_12px_28px_-22px_rgba(79,70,229,0.8)]' : 'border-[#e2e8f0] bg-white/70'} ${topic.state === 'upcoming' ? 'opacity-75' : 'hover:border-indigo-200'}`}><div className={`flex size-11 shrink-0 items-center justify-center rounded-2xl ${topic.state === 'done' ? 'bg-teal-50 text-teal-600' : topic.state === 'current' ? 'bg-indigo-50 text-indigo-600' : 'bg-slate-100 text-slate-400'}`}>{topic.state === 'done' ? <Check className="size-5" /> : <span className="font-bold">{index + 1}</span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold" dir="ltr">{topic.title}</h3>{topic.state === 'current' && <span className="rounded-full bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-600">موضوع فعلی</span>}</div><p className="mt-1 text-sm text-[#64748b]">{topic.fa}</p></div><div className="text-left"><p className="text-xs font-bold text-[#64748b]">{topic.progress}</p><ChevronLeft className="mr-auto mt-2 size-4 text-[#cbd5e1]" /></div></Link>)}</div></> }
function TopicPage() { return <><Link href="/learn" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#64748b] hover:text-indigo-600"><ArrowLeft className="size-4" />بازگشت به مسیر</Link><ShellHeader title="Food & Restaurants" subtitle="مکالمه‌ها و موقعیت‌های واقعی برای سفارش غذا، کافه و رستوران" /><div className="mb-7 flex items-center gap-4 rounded-2xl border border-[#e2e8f0] bg-white p-4"><div className="size-12 rounded-2xl bg-orange-50" /><div className="flex-1"><div className="flex justify-between text-sm font-bold"><span>پیشرفت موضوع</span><span>۳ / ۷ درس</span></div><div className="mt-3 h-2 rounded-full bg-orange-100"><div className="h-full w-[43%] rounded-full bg-[#ff8a65]" /></div></div></div><div className="grid gap-3">{lessons.map((lesson, i) => <Link href={i === 0 ? '/learn/lesson' : '#'} key={lesson} className="flex items-center gap-4 rounded-2xl border border-[#e2e8f0] bg-white p-4 transition hover:border-indigo-200"><div className={`flex size-10 items-center justify-center rounded-xl ${i < 3 ? 'bg-teal-50 text-teal-600' : i === 3 ? 'bg-indigo-50 text-indigo-600' : 'bg-slate-50 text-slate-400'}`}>{i < 3 ? <Check className="size-4" /> : <BookOpen className="size-4" />}</div><div className="min-w-0 flex-1"><h3 className="font-bold" dir="ltr">{lesson}</h3><p className="mt-1 flex items-center gap-1 text-xs text-[#94a3b8]"><Clock3 className="size-3" />{i === 0 ? '۱۰ دقیقه' : '۶ دقیقه'} · {i === 6 ? 'اختیاری' : 'ضروری'}</p></div><ChevronLeft className="size-4 text-[#cbd5e1]" /></Link>)}</div></> }
function ExploreView() { return <><div className="relative mb-6"><Search className="absolute right-4 top-1/2 size-4 -translate-y-1/2 text-[#94a3b8]" /><input aria-label="جستجوی موضوع" placeholder="موضوعی که می‌خواهی یاد بگیری..." className="h-13 w-full rounded-2xl border border-[#e2e8f0] bg-white pr-11 text-sm outline-none placeholder:text-[#94a3b8] focus:border-indigo-300" /></div><div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{explore.map((item, i) => <Link href={i === 2 ? '/learn/topic/food' : '#'} key={item} className="rounded-2xl border border-[#e2e8f0] bg-white p-5 transition hover:-translate-y-0.5 hover:border-indigo-200"><div className={`mb-4 flex size-10 items-center justify-center rounded-xl ${i % 2 ? 'bg-indigo-50 text-indigo-600' : 'bg-orange-50 text-orange-500'}`}><Compass className="size-5" /></div><p className="font-bold" dir="ltr">{item}</p><p className="mt-1 text-xs text-[#94a3b8]">موضوع منتخب</p></Link>)}</div><section className="rounded-[24px] border border-[#e2e8f0] bg-white p-6"><p className="text-xs font-bold text-teal-600">پیشنهاد امروز</p><h2 className="mt-2 text-xl font-bold">At a Café</h2><p className="mt-2 text-sm text-[#64748b]">برای مو��عیت‌هایی که هر روز ممکن است اتفاق بیفتند.</p><Link href="/learn/lesson" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#4f46e5] px-4 py-3 text-sm font-bold text-white">شروع درس <ArrowLeft className="size-4" /></Link></section></> }
function LessonPage() { return <div className="mx-auto max-w-3xl"><Link href="/learn/topic/food" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#64748b] hover:text-indigo-600"><ArrowLeft className="size-4" />Food & Restaurants</Link><header className="mb-7"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-indigo-600">درس ۴ از ۷</p><h1 className="mt-2 text-3xl font-bold tracking-tight">At a Café</h1><p className="mt-2 text-[#64748b]">Ordering and customizing your drink</p></div><div className="flex size-14 items-center justify-center rounded-full border-[5px] border-indigo-100 border-t-indigo-600 text-xs font-bold text-indigo-600">۲ / ۷</div></div><div className="mt-5 flex items-center gap-4 text-xs text-[#64748b]"><span className="flex items-center gap-1"><Clock3 className="size-3.5" />۱۰ دقیقه</span><span>·</span><span>مکالمه و شنیدار</span></div></header><div className="flex flex-col gap-4"><ImageBlock /><DialogueBlock /><VocabularyBlock /><GrammarNote /><ListeningBlock /><PracticeBlock /><SpeakingPrompt /><LessonSummary /></div><Link href="/" className="mt-6 flex h-13 w-full items-center justify-center rounded-2xl bg-[#4f46e5] text-sm font-bold text-white hover:bg-indigo-700">بازگشت به امروز</Link></div>}
function Sidebar() { return <aside className="hidden w-64 shrink-0 border-l border-[#e2e8f0] bg-white px-5 py-7 lg:block"><Link href="/" className="mb-12 flex items-center gap-3 px-2"><div className="flex size-10 items-center justify-center rounded-xl bg-[#4f46e5] text-white"><BookOpen className="size-5" /></div><span className="text-xl font-extrabold tracking-tight">Learnest</span></Link><nav className="flex flex-col gap-2"><Link href="/" className="flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold text-[#64748b] hover:bg-slate-50"><Home className="size-5" />خانه</Link><Link href="/learn" className="flex items-center gap-3 rounded-2xl bg-indigo-50 px-4 py-3 text-sm font-semibold text-[#4f46e5]"><BookOpen className="size-5" />یادگیری</Link><Link href="/practice" className="flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold text-[#64748b] hover:bg-slate-50"><Target className="size-5" />تمرین</Link><Link href="#" className="flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold text-[#64748b]"><TrendingUp className="size-5" />پیشرفت</Link><Link href="#" className="flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold text-[#64748b]"><UserRound className="size-5" />پروفایل</Link></nav></aside> }
function MobileNav() { return <nav className="fixed inset-x-0 bottom-0 z-20 border-t border-[#e2e8f0] bg-white/95 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg items-center justify-around"><Link href="/" className="flex flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold text-[#94a3b8]"><Home className="size-5" />خانه</Link><Link href="/learn" className="flex flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold text-indigo-600"><BookOpen className="size-5" />یادگیری</Link><Link href="/practice" className="flex flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold text-[#94a3b8]"><Target className="size-5" />تمرین</Link><Link href="#" className="flex flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold text-[#94a3b8]"><UserRound className="size-5" />پروفایل</Link></div></nav> }
