'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Check, ChevronLeft, Headphones, Lightbulb, RotateCcw, Target, Volume2, X } from 'lucide-react'

type PracticeView = 'hub' | 'mistakes' | 'detail' | 'review'

const buttonClass = 'inline-flex items-center justify-center gap-2 rounded-xl bg-[#4f46e5] px-4 py-3 text-sm font-bold text-white transition hover:bg-indigo-700'
const softCard = 'rounded-[24px] border border-[#e2e8f0] bg-white p-5 shadow-[0_12px_34px_-30px_rgba(15,23,42,0.55)] sm:p-6'

export function PracticeApp({ view = 'hub' }: { view?: PracticeView }) {
  return <div dir="rtl" className="min-h-screen bg-[#f8fafc] text-[#0f172a]"><div className="mx-auto min-h-screen max-w-3xl px-5 py-7 pb-24 sm:px-8 lg:py-10">{view === 'hub' && <PracticeHub />}{view === 'mistakes' && <MistakesPage />}{view === 'detail' && <MistakeDetail />}{view === 'review' && <ReviewFlow />}</div></div>
}

function Header({ title, subtitle, back = '/practice' }: { title: string; subtitle: string; back?: string }) { return <header className="mb-8"><Link href={back} className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#64748b] hover:text-indigo-600"><ArrowLeft className="size-4" />تمرین</Link><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm leading-7 text-[#64748b] sm:text-base">{subtitle}</p></header> }

function PracticeHub() { return <><Header title="تمرین" subtitle="تمرین‌هایی که بر اساس وضعیت یادگیریت برات آماده شده." /><div className="grid gap-3"><PracticeCard icon={RotateCcw} title="مرور هوشمند" subtitle="مواردی که وقت مرورشان رسیده" meta="5 words · 2 mistakes · ~4 min" href="/practice/review" cta="شروع مرور" tone="teal" /><PracticeCard icon={Target} title="اشتباه‌های من" subtitle="چیزهایی که Learnest فهمیده بهتره دوباره تمرین کنی" meta="3 active topics" href="/practice/mistakes" cta="مشاهده" tone="coral" /><PracticeCard icon={Headphones} title="تمرین مکالمه" subtitle="با موقعیت‌های واقعی صحبت کن" href="/speak" cta="شروع" tone="blue" /><PracticeCard icon={Volume2} title="لغت‌های من" subtitle="مرور لغت‌های ذخیره‌شده و جدید" href="#" cta="مشاهده" tone="indigo" /></div></> }

function PracticeCard({ icon: Icon, title, subtitle, meta, href, cta, tone }: { icon: typeof Target; title: string; subtitle: string; meta?: string; href: string; cta: string; tone: string }) { const colors: Record<string, string> = { teal: 'bg-teal-50 text-teal-600', coral: 'bg-orange-50 text-[#f06b58]', blue: 'bg-blue-50 text-blue-600', indigo: 'bg-indigo-50 text-indigo-600' }; return <article className={`${softCard} flex items-center gap-4`}><div className={`flex size-12 shrink-0 items-center justify-center rounded-2xl ${colors[tone]}`}><Icon className="size-5" /></div><div className="min-w-0 flex-1"><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm leading-6 text-[#64748b]">{subtitle}</p>{meta && <p className="mt-2 text-xs text-[#94a3b8]" dir="ltr">{meta}</p>}</div><Link href={href} className="shrink-0 rounded-xl bg-[#f0f1ff] px-3 py-2.5 text-xs font-bold text-indigo-600">{cta}</Link></article> }

const mistakes = [{ title: 'Since vs For', category: 'Grammar', meta: '3 mistakes · Last mistake: today', status: 'Needs practice', tone: 'rose' }, { title: 'Articles: a / the', category: 'Grammar', meta: '2 mistakes · Last mistake: 2 days ago', status: 'Improving', tone: 'amber' }, { title: 'Present Perfect', category: 'Grammar', meta: '2 mistakes', status: 'Improving', tone: 'amber' }, { title: 'Café vocabulary', category: 'Vocabulary', meta: '', status: 'Familiar', tone: 'teal' }]
function MistakesPage() { return <><Header title="اشتباه‌های من" subtitle="اشتباه‌هایی که تکرار شدن یا نیاز به تمرین بیشتری دارن." /><div className="grid gap-3">{mistakes.map((mistake, index) => <Link href={index === 0 ? '/practice/mistakes/since-for' : '#'} key={mistake.title} className={`${softCard} flex items-center gap-4 transition hover:-translate-y-0.5 hover:border-indigo-200`}><div className={`flex size-11 shrink-0 items-center justify-center rounded-2xl ${mistake.tone === 'rose' ? 'bg-rose-50 text-rose-500' : mistake.tone === 'amber' ? 'bg-amber-50 text-amber-600' : 'bg-teal-50 text-teal-600'}`}><Target className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold" dir="ltr">{mistake.title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-[#64748b]">{mistake.category}</span></div>{mistake.meta && <p className="mt-2 text-xs text-[#94a3b8]">{mistake.meta}</p>}</div><div className="text-left"><span className="text-xs font-bold text-[#64748b]">{mistake.status}</span>{index < 3 && <p className="mt-2 text-xs font-bold text-indigo-600">تمرین</p>}</div><ChevronLeft className="size-4 text-[#cbd5e1]" /></Link>)}</div></> }

function MistakeDetail() { const [explain, setExplain] = useState(false); return <><Header title="Since vs For" subtitle="یک نکته‌ی کوچک که با چند تمرین بهتر جا می‌افتد." back="/practice/mistakes" /><section className={softCard}><h2 className="text-lg font-bold">چرا اینجا هست؟</h2><p className="mt-3 leading-7 text-[#64748b]">این هفته دوبار در استفاده از <b dir="ltr">Since</b> و <b dir="ltr">For</b> اشتباه داشتی.</p><div className="mt-6 grid gap-3"><Example your="I have lived here for 2020." correct="I have lived here since 2020." /><Example your="She has worked here since three years." correct="She has worked here for three years." /></div><button onClick={() => setExplain(true)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#fff7ed] px-4 py-3 text-sm font-bold text-[#c45d3d]"><Lightbulb className="size-4" />چرا؟</button></section><Link href="/practice/mistakes/since-for/practice" className={`${buttonClass} mt-4 w-full`}>تمرین هدفمند <ArrowLeft className="size-4" /></Link>{explain && <Explanation onClose={() => setExplain(false)} />}</> }
function Example({ your, correct }: { your: string; correct: string }) { return <div className="rounded-2xl bg-[#f8fafc] p-4"><p className="text-xs font-bold text-[#94a3b8]">پاسخ تو</p><p className="mt-2 text-sm" dir="ltr">{your}</p><p className="mt-4 text-xs font-bold text-teal-600">درست</p><p className="mt-2 text-sm font-semibold text-teal-700" dir="ltr">{correct}</p></div> }
function Explanation({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-30 flex items-end justify-center bg-slate-950/25 p-0 sm:items-center sm:p-5" onClick={onClose}><section role="dialog" aria-modal="true" aria-labelledby="explanation-title" onClick={(event) => event.stopPropagation()} className="w-full rounded-t-[28px] bg-white p-6 pb-8 shadow-2xl sm:max-w-lg sm:rounded-[28px]"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-indigo-600">توضیح کوتاه برای همین اشتباه</p><h2 id="explanation-title" className="mt-2 text-xl font-bold">چرا <span dir="ltr">since</span>؟</h2></div><button onClick={onClose} aria-label="بستن" className="rounded-xl p-2 text-[#64748b] hover:bg-slate-100"><X className="size-5" /></button></div><p className="mt-5 leading-8 text-[#475569]">وقتی درباره نقطه شروع یک بازه زمانی صحبت می‌کنیم، از <b dir="ltr">since</b> استفاده می‌کنیم.</p><div className="mt-5 grid gap-2 text-sm"><p className="rounded-xl bg-indigo-50 p-3" dir="ltr"><b>since</b> → starting point</p><p className="rounded-xl bg-teal-50 p-3" dir="ltr"><b>for</b> → duration</p></div><div className="mt-5 grid gap-2 text-sm" dir="ltr"><p>I have lived here since 2020.</p><p>I have lived here for four years.</p></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><button className="rounded-xl border border-[#e2e8f0] px-3 py-3 text-xs font-bold">مثال بیشتر</button><button className="rounded-xl border border-[#e2e8f0] px-3 py-3 text-xs font-bold">ساده‌تر توضیح بده</button><Link href="/practice/mistakes/since-for/practice" className="rounded-xl bg-[#4f46e5] px-3 py-3 text-center text-xs font-bold text-white">تمرینش کنیم</Link></div></section></div> }

function TargetedPractice() { const [choice, setChoice] = useState<string | null>(null); const correct = choice === 'since'; return <><Header title="تمرین هدفمند" subtitle="Since vs For · یک سؤال کوتاه برای تقویت همین نکته." back="/practice/mistakes/since-for" /><section className={`${softCard} ${choice && !correct ? 'border-rose-200 bg-rose-50/70' : choice && correct ? 'border-teal-200 bg-teal-50/70' : ''}`}><p className="text-sm font-bold text-[#64748b]">جای خالی را پر کن</p><p className="mt-5 text-xl font-bold" dir="ltr">I have worked here ___ 2021.</p><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">{['for', 'since', 'during', 'from'].map((option) => <button key={option} onClick={() => setChoice(option)} className={`rounded-xl border p-3 text-sm font-bold transition ${choice === option ? option === 'since' ? 'border-teal-400 bg-teal-100 text-teal-700' : 'border-rose-300 bg-rose-100 text-rose-700' : 'border-[#e2e8f0] bg-white hover:border-indigo-300'}`} dir="ltr">{option}</button>)}</div>{choice && <div className="mt-5 rounded-2xl bg-white/75 p-4 text-sm"><p className={`font-bold ${correct ? 'text-teal-700' : 'text-rose-700'}`}>{correct ? 'درسته ✓' : 'تقریباً درست بود.'}</p>{!correct && <><p className="mt-3 text-[#64748b]">پاسخ تو: <b dir="ltr">{choice}</b></p><p className="mt-1 text-[#64748b]">پاسخ درست: <b dir="ltr">since</b></p><Link href="/practice/mistakes/since-for" className="mt-4 inline-flex text-xs font-bold text-indigo-600">Ask Learnest — چرا since درسته؟</Link></>}{correct && <p className="mt-2 leading-7 text-[#64748b]">چون 2021 یک نقطه شروع است، نه مدت زمان.</p>}</div>}</section>{choice === 'since' && <Link href="/practice/review" className={`${buttonClass} mt-4 w-full`}>بعدی <ArrowLeft className="size-4" /></Link>}</> }

function ReviewFlow() { const [shown, setShown] = useState(false); const [confidence, setConfidence] = useState<string | null>(null); const [done, setDone] = useState(false); if (done) return <><Header title="مرور امروز تمام شد ✓" subtitle="مرور شد؛ حالا Learnest می‌داند کدام مورد را دوباره به تو نشان بدهد." /><section className={`${softCard} bg-teal-50/60`}><div className="grid gap-4 text-sm"><p>۵ لغت مرور شد</p><p>۲ اشتباه تمرین شد</p><p>۱ مورد بهبود پیدا کرد</p></div></section><Link href="/" className={`${buttonClass} mt-4 w-full`}>بازگشت به امروز <ArrowLeft className="size-4" /></Link></>; return <><Header title="مرور امروز" subtitle="این موارد رو وقتی می‌بینی که بیشترین ارزش مرور رو دارن." /><section className="mb-4 grid grid-cols-3 gap-2"><ReviewStat value="5" label="لغت" /><ReviewStat value="2" label="اشتباه" /><ReviewStat value="4 min" label="زمان تقریبی" /></section><section className={softCard}><p className="text-xs font-bold text-teal-600">Vocabulary · ۱ از ۵</p><div className="mt-6 flex items-center justify-between gap-3"><h2 className="text-3xl font-bold" dir="ltr">opportunity</h2><button aria-label="پخش تلفظ" className="flex size-11 items-center justify-center rounded-full bg-indigo-50 text-indigo-600"><Volume2 className="size-5" /></button></div><p className="mt-4 text-sm text-[#64748b]" dir="ltr">This is a great opportunity to practice English.</p>{shown ? <p className="mt-5 rounded-2xl bg-[#f8fafc] p-4 text-lg font-bold">فرصت</p> : <button onClick={() => setShown(true)} className="mt-5 rounded-xl border border-indigo-200 px-4 py-3 text-sm font-bold text-indigo-600">نمایش معنی</button>}{shown && <div className="mt-5 grid grid-cols-3 gap-2">{['سخت بود', 'یادم بود', 'آسون بود'].map((item) => <button key={item} onClick={() => setConfidence(item)} className={`rounded-xl border px-2 py-3 text-xs font-bold ${confidence === item ? 'border-indigo-400 bg-indigo-50 text-indigo-700' : 'border-[#e2e8f0]'}`}>{item}</button>)}</div>}</section>{confidence && <section className={`${softCard} mt-4`}><p className="text-xs font-bold text-[#64748b]">Mistakes · ۱ از ۲</p><h2 className="mt-4 font-bold" dir="ltr">She has lived in Tehran ___ three years.</h2><button onClick={() => setDone(true)} className={`${buttonClass} mt-5 w-full`}>بررسی پاسخ: for <Check className="size-4" /></button></section>}</> }
function ReviewStat({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl bg-white p-3 text-center"><p className="font-bold" dir="ltr">{value}</p><p className="mt-1 text-[10px] text-[#64748b]">{label}</p></div> }

export { TargetedPractice }
