'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Check, ChevronLeft, Headphones, Mic2, Pause, Play, RotateCcw, Sparkles, Volume2, X, Zap } from 'lucide-react'

const feedback = { meaning: 'واضح بود', grammar: 'خوب', suggestion: 'Can I get a coffee, please?' }

type StudioState = 'intro' | 'recording' | 'processing' | 'response' | 'feedback' | 'complete'

export function SignalStudio() {
  const [state, setState] = useState<StudioState>('intro')
  const [tutorOpen, setTutorOpen] = useState(false)
  const startRecording = () => { setState('recording'); window.setTimeout(() => { setState('processing'); window.setTimeout(() => setState('response'), 700) }, 1100) }
  return <div dir="rtl" className="min-h-screen bg-[#081220] text-[#f8fafc] selection:bg-[#14b8a6]/30">
    <div className="mx-auto min-h-screen max-w-5xl px-5 pb-10 sm:px-8">
      <header className="flex items-center justify-between py-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold text-[#94a3b8] transition hover:text-white"><ChevronLeft className="size-4" />خروج</Link><div className="text-center"><p className="text-xs font-semibold tracking-[0.18em] text-[#14b8a6]">SIGNAL STUDIO</p><p className="mt-1 text-sm font-bold">Speaking Practice</p></div><button onClick={() => setTutorOpen(true)} aria-label="باز کردن Learnest Tutor" className="flex size-10 items-center justify-center rounded-xl border border-white/10 bg-[#0f2438] text-[#22d3ee] transition hover:border-[#22d3ee]/50"><Sparkles className="size-4" /></button></header>
      <div className="mx-auto max-w-2xl pt-5 sm:pt-10">
        {state !== 'complete' && <><div className="mb-7 flex items-center justify-between text-xs text-[#94a3b8]"><span>At a Coffee Shop</span><span>۳ / ۸</span></div><div className="mb-8 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[38%] rounded-full bg-[#14b8a6]" /></div>{state === 'intro' ? <Intro onStart={() => setState('response')} /> : <Conversation state={state} onRecord={startRecording} onFeedback={() => setState('feedback')} onComplete={() => setState('complete')} onRestart={() => setState('intro')} />}</>}
        {state === 'complete' && <Completion onRestart={() => setState('intro')} />}
      </div>
    </div>
    {tutorOpen && <TutorPanel onClose={() => setTutorOpen(false)} />}
  </div>
}

function Intro({ onStart }: { onStart: () => void }) { return <section className="animate-in fade-in duration-300"><div className="overflow-hidden rounded-[28px] border border-white/10 bg-[#0f2438] shadow-2xl shadow-cyan-950/20"><img src="/images/cafe-lesson.png" alt="فضای گرم یک کافه" className="h-52 w-full object-cover opacity-85 sm:h-64" /><div className="p-6 sm:p-8"><p className="text-sm font-semibold text-[#22d3ee]">تمرین مکالمه</p><h1 className="mt-3 text-2xl font-bold sm:text-3xl">At a Coffee Shop</h1><p className="mt-3 text-sm leading-7 text-[#94a3b8]">You are ordering a drink at a café.</p><p className="mt-1 text-sm leading-7 text-[#cbd5e1]">فرض کن وارد یک کافه شدی و می‌خوای سفارش بدی.</p><button onClick={onStart} className="mt-7 flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-[#14b8a6] px-5 text-sm font-bold text-[#06141f] transition hover:bg-[#2dd4bf]"><Play className="size-4 fill-current" data-icon="inline-start" />شروع مکالمه</button></div></div></section> }

function Conversation({ state, onRecord, onFeedback, onComplete, onRestart }: { state: StudioState; onRecord: () => void; onFeedback: () => void; onComplete: () => void; onRestart: () => void }) { const isResponse = state === 'response' || state === 'feedback'; return <section className="animate-in fade-in slide-in-from-bottom-2 duration-300"><div className="mb-7 flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-[#14b8a6]/15 text-[#22d3ee]"><Headphones className="size-5" /></div><div className="max-w-[calc(100%-3rem)] rounded-2xl rounded-tr-md bg-[#0f2438] p-4"><div className="flex items-center justify-between gap-5"><p className="text-xs font-bold text-[#22d3ee]">Learnest Tutor</p><button aria-label="پخش جمله" className="text-[#94a3b8] hover:text-white"><Volume2 className="size-4" /></button></div><p className="mt-3 text-lg font-semibold leading-8" dir="ltr">{isResponse ? 'Of course. Would you like it to go?' : 'What would you like to drink today?'}</p><div className="mt-3 flex items-center gap-1" aria-label="موج صوتی"><span className="h-3 w-1 rounded-full bg-[#14b8a6]" /><span className="h-6 w-1 rounded-full bg-[#22d3ee]" /><span className="h-4 w-1 rounded-full bg-[#14b8a6]" /><span className="h-8 w-1 rounded-full bg-[#22d3ee]" /><span className="h-5 w-1 rounded-full bg-[#14b8a6]" /><span className="h-3 w-1 rounded-full bg-[#22d3ee]" /></div></div></div>{state === 'feedback' && <Feedback onRestart={onRestart} onContinue={onComplete} />}{state !== 'feedback' && <><p className="mb-4 text-center text-sm text-[#94a3b8]">{state === 'recording' ? 'در حال ضبط...' : state === 'processing' ? 'دارم گوش می‌دم...' : 'جوابت رو به انگلیسی بگو'}</p>{isResponse && <div className="mb-5 rounded-2xl border border-[#14b8a6]/25 bg-[#14b8a6]/5 p-4"><p className="text-xs font-bold text-[#94a3b8]">پاسخ تو</p><p className="mt-2 text-base font-semibold" dir="ltr">I want one coffee please.</p></div>}<div className="flex justify-center"><button onClick={isResponse ? onFeedback : onRecord} disabled={state === 'processing'} aria-label={state === 'recording' ? 'در حال ضبط' : 'ضبط پاسخ'} className={`relative flex size-24 items-center justify-center rounded-full border-8 border-[#081220] bg-[#14b8a6] text-[#06141f] shadow-[0_0_0_1px_#14b8a6,0_0_45px_rgba(20,184,166,.28)] transition hover:bg-[#2dd4bf] disabled:animate-pulse`}><Mic2 className="size-8" /></button></div><p className="mt-4 text-center text-xs text-[#64748b]">{isResponse ? 'برای دیدن بازخورد، ادامه بده' : 'برای شروع، دکمه میکروفون را بزن'}</p></>}</section> }

function Feedback({ onRestart, onContinue }: { onRestart: () => void; onContinue: () => void }) { return <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-[#0f2438] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">بازخورد کوتاه</h2><span className="text-xs text-[#14b8a6]">همین الان</span></div><div className="grid grid-cols-2 gap-3 text-sm"><p className="rounded-xl bg-white/5 p-3"><span className="block text-xs text-[#94a3b8]">معنی</span><b className="mt-1 block text-[#5eead4]">✓ واضح بود</b></p><p className="rounded-xl bg-white/5 p-3"><span className="block text-xs text-[#94a3b8]">Grammar</span><b className="mt-1 block text-[#5eead4]">✓ خوب</b></p></div><p className="mt-4 text-xs text-[#94a3b8]">Natural English</p><p className="mt-2 rounded-xl bg-[#14b8a6]/10 p-3 text-sm font-semibold text-[#99f6e4]" dir="ltr">{feedback.suggestion}</p><p className="mt-4 text-xs text-[#94a3b8]">Pronunciation</p><p className="mt-1 text-sm font-semibold">Good</p></div><div className="grid gap-2 sm:grid-cols-2"><button onClick={onRestart} className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-[#cbd5e1]">دوباره بگم</button><button onClick={onContinue} className="rounded-xl bg-[#14b8a6] px-4 py-3 text-sm font-bold text-[#06141f]">ادامه مکالمه</button></div></div> }

function Completion({ onRestart }: { onRestart: () => void }) { return <section className="animate-in fade-in zoom-in-95 duration-300"><div className="mb-6 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#14b8a6]/15 text-[#5eead4]"><Check className="size-8" /></div><h1 className="mt-5 text-3xl font-bold">جلسه تمام شد</h1><p className="mt-2 text-sm text-[#94a3b8]">یک قدم خوب برای مکالمه امروزت.</p></div><div className="rounded-[24px] border border-white/10 bg-[#0f2438] p-5"><div className="grid grid-cols-2 gap-3"><Summary label="Conversation" value="Good" /><Summary label="Natural English" value="Improving" /><Summary label="Pronunciation" value="Good" /><Summary label="New expressions" value="2" /><Summary label="Mistakes remembered" value="1" /></div><p className="mt-5 rounded-2xl bg-[#14b8a6]/10 p-4 text-sm leading-7 text-[#99f6e4]">یک نکته وارد مرور فردات شد.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={onRestart} className="flex items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-sm font-bold"><RotateCcw className="size-4" />تمرین دوباره</button><Link href="/" className="flex items-center justify-center gap-2 rounded-xl bg-[#14b8a6] px-4 py-3 text-sm font-bold text-[#06141f]">برگشت به امروز <ArrowLeft className="size-4" /></Link></div></section> }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-[#94a3b8]">{label}</p><p className="mt-1 font-bold">{value}</p></div> }

function TutorPanel({ onClose }: { onClose: () => void }) { const [explained, setExplained] = useState(false); const [selected, setSelected] = useState(''); const actions = ['این درس رو ساده‌تر توضیح بده', 'ازم تمرین بگیر', 'یک مثال دیگه بزن', 'تفاوت این دو جمله چیه؟', 'با من مکالمه تمرین کن']; return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-5" onClick={onClose}><aside role="dialog" aria-modal="true" aria-labelledby="tutor-title" onClick={e => e.stopPropagation()} className="w-full max-w-lg rounded-t-[28px] border border-white/10 bg-[#0f2438] p-6 shadow-2xl sm:rounded-[28px]"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-wide text-[#22d3ee]">AI TUTOR</p><h2 id="tutor-title" className="mt-2 text-xl font-bold">Learnest Tutor</h2><span className="mt-2 inline-flex rounded-full bg-[#14b8a6]/15 px-2.5 py-1 text-[11px] font-bold text-[#5eead4]">A2 · Food & Restaurants</span></div><button onClick={onClose} aria-label="بستن" className="rounded-xl p-2 text-[#94a3b8] hover:bg-white/10"><X className="size-5" /></button></div><div className="mt-6 grid gap-2">{actions.map(action => <button key={action} onClick={() => setSelected(action)} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-3 text-right text-sm text-[#cbd5e1] transition hover:border-[#14b8a6]/50"><span>{action}</span><ArrowLeft className="size-4 text-[#14b8a6]" /></button>)}</div>{selected && <div className="mt-4 rounded-2xl bg-white/5 p-4 text-sm leading-7 text-[#cbd5e1]"><p className="font-bold text-white">برای «{selected}»</p><p className="mt-2">در این موقعیت، جمله‌ی <span dir="ltr" className="font-semibold text-[#99f6e4]">Can I get a coffee to go?</span> یک روش طبیعی و مودبانه برای سفارش در کافه است.</p><button onClick={() => setExplained(!explained)} className="mt-3 text-xs font-bold text-[#22d3ee]">توضیح فارسی</button>{explained && <p className="mt-2 rounded-xl bg-[#14b8a6]/10 p-3 text-[#99f6e4]">این جمله یعنی: می‌تونم یک قهوه برای بیرون‌بر بگیرم؟</p>}</div>}</aside></div> }

export function SignalStudioButton() { return <Link href="/speak" className="inline-flex items-center gap-2 rounded-xl bg-[#4f46e5] px-4 py-3 text-sm font-bold text-white"><Mic2 className="size-4" />Speaking</Link> }

export function AskLearnestButton({ label = 'Ask Learnest' }: { label?: string }) { return <Link href="/tutor" className="inline-flex items-center gap-2 text-xs font-bold text-indigo-600"><Sparkles className="size-3.5" />{label}</Link> }
